// 在这里导出所有的action
export default {
    THEME_CHANGE: "THEME_CHANGE",  // 改变主题
    THEME_INIT: "THEME_INIT",      // 主题初始化
    POPULAR_REFRESH: "POPULAR_REFRESH",
    LOAD_POPULAR_FAIL: "LOAD_POPULAR_FAIL",
    LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS",
    };
